### ISSUE TITLE
Wiki: ENBSeries setting is EnableDynamicCubemap

### ISSUE THREAD

**Issue by junip0r** [hakasapl/ParallaxGen#132]
![image](https://github.com/user-attachments/assets/945dff7e-0b22-406c-a30a-147e01dce9be)

Should be `EnableDynamicCubemap`, not `EnableDynamicCubemaps`.

http://enbdev.com/mod_tesskyrimse_v0499.htm

**Comment by hakasapl** [comment]
Fixed, thanks!
