### ISSUE TITLE
v0.7.2: MO2 profile selection no longer works

### ISSUE THREAD

**Issue by junip0r** [hakasapl/ParallaxGen#140]
Select my instance:
![image](https://github.com/user-attachments/assets/22a299f9-1d0d-4eea-bdb4-d1cf8e5107d8)

Select profile:
![image](https://github.com/user-attachments/assets/d45ee62d-267b-4194-913f-2a17c4cd7614)

Issue does not occur when using v0.7.1.

**Comment by hakasapl** [comment]
You need to select what MO2 calls the "instance folder". If you press the folder icon in MO2 then click on open instance folder you'll get there. The folder with modorganizer.ini in it is required. So not the base folder, but the instance folder

**Comment by junip0r** [comment]
Many thanks, that worked. So after installing `d3dcompiler_47`, everything seems to be working on v0.7.2, including GPU acceleration.
![image](https://github.com/user-attachments/assets/fb8ba671-2d2d-4be5-baae-a850d5b77b42)
_Upgrade Parallax to Complex Material_ gives me 3.5 gigabytes of output. Both configs shown below ran successfully. It did freeze on me twice during mesh patching but I've had more successes than failures. Thanks for your help, and for making ParallaxGen!
![0](https://github.com/user-attachments/assets/0593270c-2b91-4233-b193-68e04a87d49f)
![1](https://github.com/user-attachments/assets/b42f88ad-9dbb-4f95-8d38-ba617eb2d878)

**Comment by junip0r** [comment]
👍

**Comment by hakasapl** [comment]
Oh you got GPU to work?! Awesome! I will update the section on nexus describing this

There is a thread gridlock I'm working on fixing in 0.7.2, will release a hotfix soon. That's very likely the reason for the freezes.
