### ISSUE TITLE
v0.7.1: Very little output on Linux

### ISSUE THREAD

**Issue by junip0r** [hakasapl/ParallaxGen#141]
I'm not sure what "correct" output looks like but this is what I get on Linux, which seems a little sparse? Does this look correct or broken to you? I have many, many mods providing textures and meshes with parallax and/or complex materials.

![image](https://github.com/user-attachments/assets/074339e1-f9ea-45d0-ac75-6b766a68ee82)

![image](https://github.com/user-attachments/assets/42ff4b1d-66a1-44a2-b965-1b94e8a39b38)

**Comment by hakasapl** [comment]
Yeah that's a blank output. Do you have a log?

**Comment by junip0r** [comment]
Fixed with `winetricks d3dcompiler_47`.

**Comment by junip0r** [comment]
👍
