### ISSUE TITLE
v0.7.2: DynCubemap Blocklist disappearing after relaunching 

### ISSUE THREAD

**Issue by OSRSEdenGuard** [hakasapl/ParallaxGen#142]
When launching the program with **Show Advanced Options** ticked the **DynCubemap Blocklist** does not appear.

![image](https://github.com/user-attachments/assets/22279192-6090-401a-813a-6ae0b3ccf7c5)

Toggling **Show Advanced Options** off and on again, or **Load Config** makes it reappear.

![image](https://github.com/user-attachments/assets/d886021d-2b36-4d58-9317-40c42b16d985)

**Comment by hakasapl** [comment]
Thanks, confirmed. Will fix in next release
