### ISSUE TITLE
For plugin patches that cannot apply we should apply a basic set of textures instead

### ISSUE THREAD

**Issue by hakasapl** [hakasapl/ParallaxGen#22]
For PBR: 255 red, 0 green, 255 blue, 255 alpha
For CM: black env mask with white alpha
For parallax: 127 height map

This way the shader won't break

**Comment by Sebastian-81** [comment]
- neutral height maps should have the value 127, black would shift the texture
- additional, for complex material, according to this: [Complex Materail](https://modding.wiki/en/skyrim/developers/complex-parallax-materials) parallax can be turned completely off if all alpha values are 255

**Comment by Sebastian-81** [comment]
I double checked in-game with CS 0.8.7 - 255 alpha value in complex material texture turns parallax effect off

**Comment by hakasapl** [comment]
Some additional notes on this:

* The patchers are called generically now (they fit an interface). So it would be good for the patcher to provide the path to each generic texture.
* The texture should be in the assets folder
* The texture will need to be moved to the output (see how that's happening with the dyncubemap file in main)
