### ISSUE TITLE
Better way for ParallaxGen to identify textures across incompatible mods

### ISSUE THREAD

**Issue by hakasapl** [hakasapl/ParallaxGen#24]
## Current use cases that are problematic

1. Overwrites in loose files that result in a diffuse/normal not matching with env mask/height map
    1. For example, adding a non-parallax and non-CM retexture after an AIO that has parallax or CM, ParallaxGen will use the height map / env mask of the AIO in combination with the new diffuse, resulting in issues.
1. Inferior shaders overwriting superior ones
    1. For example, a user might install a parallax mod that has height maps. If a matching CM env mask existing higher up in the loose file load order, ParallaxGen will use that instead, resulting in issues.
1. Wanting to use an env mask from `--upgrade-shaders` instead of the env mask already in the load order
    1. For example if we wanted to use a parallax mod with CM, currently --upgrade-shaders won't generate an env mask because an existing env mask already exists.

**The core issue is that ParallaxGen cannot identify whether a diffuse/normal map goes with a height/env mask map**

## Potential Solutions

1. Use image processing techniques to determine if diffuse/normal goes with height/env mask
    1. *This was attempted unsuccessfully using edge detection techniques, among others. For some things it worked, but there was a lot of false results*
1. Use an ML model to determine if they match
    1. Requires a large dataset of maps that both go together and that do not go together. This would require using modder's assets to train the dataset - use permissions?
    1. Will never be 100% accurate - the nature of ML
1. Hooking mod managers
    1. Will require support for MO2 and vortex, and it would have to be optional, some people still use wyre bash etc.

## Mod Manager Solution

1. Figure out a way we can map a specific texture to the loose file load order (so we can see if two files are above or below on the loose file load order from each other)
1. Use that info to decide the shader. The winning texture becomes the shader (ie. parallax could win over CM if it's further down in the loose file load order)
1. In the case of `--upgrade-shaders`, if a parallax map is higher priority than a CM map, it should still make a new CM map with that parallax map instead of skipping.

@Sebastian-81 thoughts?

**Comment by Sebastian-81** [comment]
I also see the Mod manager solution as the most reliable solution and we could make it optional in case someone does not want to use a mod manager. Also as a first step we could:

- Output a summary of parallax and cm material maps found and their corresponding diffuse maps and their origin, BSA or loose. This could be part of a larger summary project which I think could be very useful in general. DynDoLod uses HTML and very detailed descriptions which I find help a lot
- Use the mod manager extension mechanisms to at least warn the user if
-- a parallax map is installed without a diffuse map
-- a diffuse map is installed and an existing parallax map of the same name is already present

**Comment by Sebastian-81** [comment]
I just had another idea: The report could show small previews of the used height map, cm map and their corresponding diffuse texture. Then it would be very easy to spot if there is a mismatch.

**Comment by Sebastian-81** [comment]
I just realized that we can find files in the staging folder of the mod manager, for Vortex it would be `C:\ProgramData\vortex\skyrimse\mods` - there we can do a mapping of the textures to the mod for the summary and output a warning in the summary when the diffuse texture is from a different directory than the parallax texture

**Comment by Sebastian-81** [comment]
As discussed: MO2 has the same folder, so we can make use of that folder information. For MO2 there is also a load order file that can be used

### Use case find out if parallax and diffuse don't match:
If the user specifiec an command line argument with the MOD staging folder, we create a summary file that give mod names if one mod contains the diffuse and the other the parallax map based on the load order. This is ensured by comparing the actual file used in the data folder via hash and filename to the one of the staging folder. The folder where this texture lies is the winning mod.

- pre-fill file map from directories with hash and filename
- ouput file with summary of mismatches
- the config file has a list of mod pairs that are allowed, i.e. where the parallax was added after the original mod was created

**Comment by hakasapl** [comment]
I have an implementation based on @Sebastian-81 's PR in [mod-priority-system branch](https://github.com/hakasapl/ParallaxGen/tree/mod_priority_system). I will describe the user-facing side of how this works:

## Environment Setup

1. MO2 users need to specify 2 CLI arguments: `-m "mo2" --mo2-instance-dir="<path/to/instance>"`. Optionally, users can also specify the MO2 profile to read with `--mo2-profile="<profile name>"`. The default is to user the profile named `Default`
2. Vortex users need to specify just 1 CLI argument: `-m "vortex"`. Everything else is auto detected since vortex leaves a JSON with all that info in the data folder

Not specifying any of these arguments results in old behavior.

## Mod Priorities

In the ParallaxGen config you can define a list of mods as a parallaxgen load order under the `mod_loadorder` field. **Mods that are later in the list have higher priority**. **Mods that are not in the list have lower priority than those defined in the list (so users don't need to define every mod they have here)** So, the way the priority works is that everything not defined gets a priority of `-1`, and the first element of the list gets priority `0`, and counts up from there. Higher numbers have higher priority (though that numbering system is not exposed to the user)

When figuring out what shader to patch a shape as, **every** shader is checked and the one that uses files from the highest priority mod wins. If there are multiple shaders that would work with the same priority, the best shader wins (PBR > CM > Parallax).

For PBR, the mod priority system applied to patcher JSONs as well. Higher priority mods will have their JSONs a higher priority than lower priority ones (if same priority ordering is alphabetical like it always has been)

## Shader Upgrades

Before parallax maps were not upgraded to CM if an existing CM map existed. Now if a parallax mod has higher priority than the mod with the CM map, it will be upgraded and used instead of the CM map.

## Other Things

Warnings will be posted in the console if a diffuse/normal doesn't come from the same mod as the height map or CM map etc. Most of the time this is intentional (for example skyland aio + skyland complex material is 2 different mods), but it's there as a tool nonetheless to spot those that are not intentional.

**Comment by hakasapl** [comment]
Mod priority system merged
