### ISSUE TITLE
Dealing with env scale = 0

### ISSUE THREAD

**Issue by hakasapl** [hakasapl/ParallaxGen#28]
Some meshes have env scale = 0 which screws up complex material. How can we deal with this?

Options:
* Set anything with 0 env scale to 1.0
* Set anything with non-1.0 env scale to 1.0 (only for CM)

**Comment by Sebastian-81** [comment]
For complex material is always needs to be 1 ?

**Comment by hakasapl** [comment]
vanilla env shaders we shouldn't mess with. I think for CM we can just set it to 1.0 based on Leo's comments

**Comment by hakasapl** [comment]
This is merged
