### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by langfod** [hakasapl/ParallaxGen#5]
parallaxgen seem to just quit after:

[2024-07-22 20:55:38.894] [ParallaxGen] [info] Adding loose files to file map.

ParallaxGen.exe --optimize-meshes --upgrade-shaders --no-zip --no-cleanup -v -d "\SteamLibrary\steamapps\common\Skyrim Special Edition"
[ParallaxGen.log](https://github.com/user-attachments/files/16341447/ParallaxGen.log)

ParallaxGen.exe --optimize-meshes --upgrade-shaders --no-zip --no-cleanup -vv -d "\SteamLibrary\steamapps\common\Skyrim Special Edition"
[ParallaxGen.zip](https://github.com/user-attachments/files/16341462/ParallaxGen.zip)

**Comment by hakasapl** [comment]
@langfod thanks. Can you try running your load order on this build that I've attached? I added some extra error handling around loose files hopefully that will tell us something:

[artifacts-parallaxgen.zip](https://github.com/user-attachments/files/16342929/artifacts-parallaxgen.zip)

**Comment by langfod** [comment]
it may be running will post log when done

did note these:

[2024-07-22 22:39:56.447] [ParallaxGen] [warning] Failed to add loose file to map, skipping \SteamLibrary\steamapps\common\Skyrim Special Edition\Data\meshes\actors\character\Kangmina Serana\Clothes\SMPxml\MS3_Skirt_SMP_CBBE.xml.Ω░Ç∞è┤ δ│┤∞ºÇ δ│╕ ∞é¡∞á£ - δ│╡∞é¼δ│╕: No mapping for the Unicode character exists in the target multi-byte code page.
[2024-07-22 22:39:56.448] [ParallaxGen] [warning] Failed to add loose file to map, skipping \SteamLibrary\steamapps\common\Skyrim Special Edition\Data\meshes\actors\character\Kangmina Serana\Clothes\SMPxml\MS3_Skirt_SMP_CBBE.xml.∞¢Éδ│╕: No mapping for the Unicode character exists in the target multi-byte code page.

**Comment by hakasapl** [comment]
I take it that file isn't actually names like that haha, but that's the reason for the crash, not sure where those extra chars come from

**Comment by langfod** [comment]
hey may be actually (korean):

MS3_Skirt_SMP_CBBE.xml.Delete Chest Pussy Bone - Copy
MS3_Skirt_SMP_CBBE.xml.Original

![Screenshot 2024-07-22 225214](https://github.com/user-attachments/assets/d2830cb0-d466-4b2d-9496-269599ab1dd4)

**Comment by langfod** [comment]
This is just -v :

[ParallaxGen.log](https://github.com/user-attachments/files/16343168/ParallaxGen.log)

I can run again with -vv if needed

**Comment by langfod** [comment]
At least one more snuck through. 
Windows zip did not like although 7zip was okay


![Screenshot 2024-07-22 225832](https://github.com/user-attachments/assets/8029b7db-3c5e-4e73-bbab-2ab939f13b55)

**Comment by hakasapl** [comment]
That's a warning when you try to open the output zip with windows zip?

**Comment by langfod** [comment]
When just doing a Windows "Compress to zip files" on the output folder

**Comment by langfod** [comment]
using  --no-zip  so usure is parallaxgen would crash there yet.

**Comment by hakasapl** [comment]
Yeah could you try without `--no-zip` and let me know if it crashes due to that file as well?

**Comment by langfod** [comment]
same flags as before but -vv

[ParallaxGen.zip](https://github.com/user-attachments/files/16343299/ParallaxGen.zip)

**Comment by hakasapl** [comment]
Thanks. This version should fix the loose file crash issue without any warnings: 
[parallaxgen-artifacts-85024584d678afb274f38281fde8437a65b6a49a.zip](https://github.com/user-attachments/files/16343324/parallaxgen-artifacts-85024584d678afb274f38281fde8437a65b6a49a.zip)

**Comment by langfod** [comment]
did not have --no-zip but also no zip file and no error.

[ParallaxGen.log](https://github.com/user-attachments/files/16343338/ParallaxGen.log)

will try again with new fix

**Comment by hakasapl** [comment]
I guess it crashed since there's no complete message?

**Comment by langfod** [comment]
I might have messed it up during the run.

**Comment by langfod** [comment]
Using the last version you sent and without --no-zip

A zipfile was created.

[ParallaxGen.log](https://github.com/user-attachments/files/16343432/ParallaxGen.log)

![Screenshot 2024-07-22 234152](https://github.com/user-attachments/assets/7eb669be-40d1-42ac-a9d9-fe7829d01e1c)

**Comment by hakasapl** [comment]
Cool, can you open that zip and see if that mesh with the characters windows couldn't handle is in there as well?

If it is then I think we're all set, just a UTF-8 decoding bug that I fixed in the version I sent you. So that fix will be in the next release

**Comment by langfod** [comment]
![Screenshot 2024-07-22 234152](https://github.com/user-attachments/assets/95d8ddfa-6ce9-436c-a9e7-8712d2171ef1)

**Comment by langfod** [comment]
![Screenshot 2024-07-22 234603](https://github.com/user-attachments/assets/18c0a16e-9ee8-465e-8919-1c530eebfb5e)

**Comment by hakasapl** [comment]
Is it in the zip itself though? Since it's in the output it should be in the zip as well, I just want to make sure

**Comment by langfod** [comment]
yes that was the zip file

**Comment by hakasapl** [comment]
Great! Closing this, you can just use the build I linked to you in this issue for now but I should have the next release out soon with this fix. Thank you for your help!
