### ISSUE TITLE
Non-Ascii character handling not working

### ISSUE THREAD

**Issue by Sebastian-81** [hakasapl/ParallaxGen#96]
Uniform characters are not handled correctly which leads to errors if a filename uses non-Ascii characters on disk and BSAs. Also strings from external libraries like names of shapes in NIFs are not converted correctly.

Currently `string` in ParallaxGen is considered to be [UTF8](https://de.wikipedia.org/wiki/UTF-8) whereas `wstring` is considered to be [UTF-16](https://en.wikipedia.org/wiki/UTF-16) , the encoding of the string is ignored. So any other `string` encoding like [Latin1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1)  is converted incorrectly.

Example:
`goldbarrel01°.nif`

UTF-16 encoded:
``` 
0x0067 'g' 0x006f 'o' 0x006c 'l' 0x0064 'd' 0x0062 'b' 0x0061 'a' 0x0072 'r' 0x0072 'r' 0x0065 'e' 0x006c 'l' 
0x0030 '0' 0x0031 '1' 0x00b0 '°' 0x002e '.' 0x006e 'n' 0x0069 'i' 0x0066 'f'
```
UTF-8 encoded:
``` 
0x67 'g' 0x6f 'o' 0x6c 'l' 0x64 'd' 0x62 'b' 0x61 'a' 0x72 'r' 0x72 'r' 0x65 'e' 0x6c 'l' 
0x30 '0' 0x31 '1' 0xc2 0xb0 '°' 0x2e '.' 0x6e 'n' 0x69 'i' 0x66 'f'
```

Latin1 encoded:
``` 
0x67 'g' 0x6f 'o' 0x6c 'l' 0x64 'd' 0x62 'b' 0x61 'a' 0x72 'r' 0x72 'r' 0x65 'e' 0x6c 'l' 
0x30 '0' 0x31 '1' 0xb0 '°' 0x2e '.' 0x6e 'n' 0x69 'i' 0x66 'f'
```

**Comment by Sebastian-81** [comment]
Possible solutions:

1. Store all strings and paths as UTF-16
- conversion needed wherever the string is created and original encoding is not UTF-16
- all strings are already currently `wstring` so not much changes of the strings needed
- `std::filesystem::path` internally uses `wstring`
- Disadvantage: doubled memory usage than UTF-8, but no change regarding the current memory consumption
- If the source encoding is not known, there is still a chance that the character is correct since the first two bytes are based on [Latin1](https://en.wikipedia.org/wiki/Latin-1_Supplement)
- TBC: How to implement case insentive file path comparision?

2. Like 1 but store strings additionally in their original encoding if encoding is unknown
- code gets more complex
-  If `std::filesystem::path` is used for this, the encoding must be stored additionally and conversions gets more complex since it does not seem to be able to store `string`, it always uses `wstring` to store the path

3. Store all strings in their original encoding 
- all codepaths where comparision is needed need to be changed
-  If `std::filesystem::path` is used for this, the encoding must be stored additionally and conversions gets more complex since it does not seem to be able to store `string`, it always uses `wstring` to store the path

4. Store all strings in UTF-8
- conversion needed wherever the string is created and original encoding is not UTF-8
- very high number of code changes since currently `wstring` is used everywhere
- smaller memory consumption than UTF-16
- if the original encoding is not known there is no way to convert to UTF-8, so strings where encoding is not known must be stored separately

-> Suggestion: Solution 1 in the long term

TBC: Solution 1 or 2 for now until we know the encoding of all provided strings
Solution 1: Only works if characters are from [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement)
Solution 2: complex code that needs to be removed afterwards but only correct way if there is now way to get the original encoding

@hakasapl  please review

**Comment by hakasapl** [comment]
I think I'm leaning towards solution 1. The memory usage isn't really a concern for me, it's not an embedded app and strings are a very small part of our memory usage currently so it doesn't affect much.

As for wstring vs u16string, I think it doesn't matter what we use. Proton on linux is effectively a windows environment so wstring will stay the same. If we wanted to be more explicit we could use u16string (because the byte size of wstring chars change based on system - on windows its 2 bytes)

UTF8 everywhere would be concerning to me because what if we have an explicitly UTF16 string like a path with a code page that requires 2 bytes? It feels like there will need to be more special one-off cases, where we could generalize with 2-byte wstrings better if that makes sense

**Comment by hakasapl** [comment]
Reopening this so I remember to add exclusions to loose files - also a good test to try:

```
﻿[2024-12-03 12:30:09.832] [info] Welcome to ParallaxGen version 0.7.1!
[2024-12-03 12:30:09.832] [warning] ParallaxGen is currently in ALPHA. Please file detailed bug reports on nexus or github.
[2024-12-03 12:30:09.833] [info] Loaded 2 ParallaxGen configs successfully
[2024-12-03 12:30:21.748] [info] ParallaxGen output directory: C:\Users\Bj├â┬Ârn\ac_Games\Mods\Skyrim\Tools\ParallaxGen\ParallaxGen_Output
[2024-12-03 12:30:21.749] [info] Opening Data Folder "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data"
[2024-12-03 12:30:21.857] [error] Failed to create output directory: create_directories: unknown error: "C:\Users\Bj├Ârn\ac_Games\Mods\Skyrim\Tools\ParallaxGen\ParallaxGen_Output"
```
